<?php
$tartes = [
    "fraises" => [
        "category_id" => 1,
        "vat_id" => 2,
        "name" => "Fraises",
        "description" => "Tarte aux fraises fraîches.",
        "price" => 1500,
        "picture_url" => "https://www.patisserie-et-gourmandise.com/wp-content/uploads/2018/04/recette-tarte-fraise.jpg",
        "weight" => 1000,
        "quantity" => 50,
        "is_available" => 1,
        "discount" => 10,
    ],
    "pommes" => [
        "category_id" => 1,
        "vat_id" => 2,
        "name" => "Pommes",
        "description" => "Tarte aux pommes délicieuse.",
        "price" => 1000,
        "picture_url" => "https://i1.wp.com/www.la-gourmandise-avant-tout.com/wp-content/uploads/2020/11/tarte-aux-pomems-Cedric-Grolet-scaled.jpg?resize=1020%2C600&ssl=1",
        "weight" => 800,
        "quantity" => 30,
        "is_available" => 1,
        "discount" => 5,
    ],
    "poires" => [
        "category_id" => 1,
        "vat_id" => 2,
        "name" => "Poires",
        "description" => "Tarte aux poires juteuses.",
        "price" => 1200,
        "picture_url" => "https://fac.img.pmdstatic.net/fit/~1~fac~2022~06~27~97207b60-4031-4be3-9cbb-b3f765aeef1e.jpeg/750x562/quality/80/crop-from/center/cr/wqkgSVNUT0NLL0dFVFRZIElNQUdFUyAvIEZlbW1lIEFjdHVlbGxl/tarte-aux-poires-normande.jpeg",
        "weight" => 900,
        "quantity" => 10,
        "is_available" => 1,
        "discount" => 8,
    ],
    "cerises" => [
        "category_id" => 1,
        "vat_id" => 2,
        "name" => "Cerises",
        "description" => "Tarte aux cerises délicieuses.",
        "price" => 1600,
        "picture_url" => "https://img.static-rmg.be/a/food/image/q75/w640/h400/1092579/tarte-aux-cerises.jpg",
        "weight" => 1100,
        "quantity" => 0,
        "is_available" => 1,
        "discount" => 12,
    ],
    "abricots" => [
        "category_id" => 1,
        "vat_id" => 2,
        "name" => "Abricots",
        "description" => "Tarte aux abricots sucrés.",
        "price" => 1700,
        "picture_url" => "https://www.cakesandsweets.fr/wp-content/uploads/2012/02/tarte-abricot.jpg",
        "weight" => 950,
        "quantity" => 20,
        "is_available" => 1,
        "discount" => 7,
    ],
];
